[package]
name = "qfin-api"
authors.workspace = true
categories.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
reqwest.workspace = true
thiserror.workspace = true
tokio.workspace = true
